name: My First Workflow
on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: dragon-text-file
          path: dragon.txt

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v7.0.0
        with:
          name: dragon-text-file


      - name: Verify Content
        run: grep -i "dragon" dragon.txt